### ISSUE TITLE
tweak camera beginning and end

### ISSUE THREAD

**Issue by JeffreyMJohnson** [TeamQuestionIt/FinalProject#14]

**Comment by QuinnJMosher** [comment]
@BryceX  is working on this

**Comment by QuinnJMosher** [comment]
This was fixed wit the level1 push

**Comment by JeffreyMJohnson** [comment]
bryson says this still broken per twitter.

**Comment by QuinnJMosher** [comment]
this Is because the aspect ratio of the player is off.
when you build the program make sure that the aspect ratio is locked to 16:9 or (with the web build) make sure the dimensions given meet the aspect ratio of 16:9.
our camera and menu stuff does not take screen shape into account so we have to force it to the right shape: 16:9.

**Comment by QuinnJMosher** [comment]
fixed with the final builds
